apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-app2
  labels:
    app: go-k8s-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-app2
  template:
    metadata:
      labels:
        app: go-k8s-app2
    spec:
      containers:
        - name: go-k8s-app2
          image: go-k8s-app2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app2
spec:
  type: ClusterIP
  selector:
    app: go-k8s-app2
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001
